'use client';

import { useState, useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Brain, RefreshCw } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { aiApi } from '@/lib/api';
import { cn } from '@/lib/utils';

const MOCK_BRIEFING = `Today's news cycle is dominated by continued geopolitical tensions in Eastern Europe, where diplomatic negotiations show mixed signals. On the tech front, major AI companies announced significant model upgrades, with OpenAI and Anthropic both releasing performance benchmarks that have sparked intense industry debate. Financial markets responded cautiously to the Federal Reserve's latest meeting minutes, which suggested rates may remain elevated through Q2. Meanwhile, climate scientists published alarming new data showing accelerated Arctic ice melt, drawing calls for immediate policy action from global leaders at ongoing UN climate talks.`;

export function AiBriefing() {
  const { data, isLoading, refetch, isRefetching } = useQuery({
    queryKey: ['ai-briefing'],
    queryFn: () => aiApi.getBriefing(),
    select: (res) => (res.data as { data: { briefing: string } }).data?.briefing,
    staleTime: 5 * 60 * 1000,
    refetchInterval: 60000,
  });

  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  const briefing = data ?? MOCK_BRIEFING;

  return (
    <div className="surface-card rounded-2xl bg-gradient-to-br from-primary/5 via-card/70 to-violet-500/5 p-5">
      <div className="mb-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary/10">
            <Brain className="h-3.5 w-3.5 text-primary" />
          </div>
          <span className="text-sm font-semibold text-foreground">AI Daily Briefing</span>
          <span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-xs font-medium text-emerald-500">
            Live
          </span>
        </div>
        <button
          id="refresh-briefing"
          onClick={() => void refetch()}
          disabled={isRefetching}
          className="rounded-lg p-1.5 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground disabled:opacity-50"
          aria-label="Refresh briefing"
        >
          <RefreshCw className={cn('h-3.5 w-3.5', isRefetching && 'animate-spin')} />
        </button>
      </div>

      {isLoading ? (
        <div className="space-y-2">
          {[...Array(3)].map((_, i) => (
            <div key={i} className={cn('skeleton h-4 rounded', i === 2 && 'w-3/4')} />
          ))}
        </div>
      ) : (
        <div className="prose prose-sm prose-invert max-w-none text-muted-foreground">
          <ReactMarkdown>{briefing}</ReactMarkdown>
        </div>
      )}

      <div className="mt-3 flex items-center gap-1 text-xs text-muted-foreground">
        <span>Generated by AI ·</span>
        <span>Updated {mounted ? new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '--:--'}</span>
      </div>
    </div>
  );
}
